version: '3.5'

services:

  db:
    image: mysql:5.7
    environment:
      TZ: 'Europe/Moscow'
#      TZ: 'Asia/Yekaterinburg'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#    ports:
#      - "3306:3306"
    networks:
      - internal
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf:ro
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      restart_policy: { condition: on-failure, delay: 5s, max_attempts: 3, window: 180s}
    stop_grace_period: 1m

  activemq:
    image: bgbilling/activemq
    environment:
      TZ: 'Europe/Moscow'
#    ports:
#      - "61616:61616"
#      - "8161:8161"
    networks:
     - internal
    volumes:
      - ./activemq/activemq.xml:/opt/activemq/current/conf/activemq.xml:ro
      - ./activemq/data:/opt/activemq/current/data
    stop_grace_period: 30s

  server:
    image: bgbilling/server:7.1
    environment:
      TZ: 'Europe/Moscow'
      BGBILLING_MEMORY: '-Xmx256m'
      BGBILLING_SYSTEM_PROPERTIES: '-Dcontext.path=/bgbilling'
    ports:
      - "8080:8080"
    networks:
      - internal
    volumes:
      - ./server/data.properties:/opt/bgbilling/BGBillingServer/data/data.properties:ro
      - ./server/log4j.xml:/opt/bgbilling/BGBillingServer/data/log4j.xml:ro
      - ./server/log/:/opt/bgbilling/BGBillingServer/log/
      - ./server/dyn/:/opt/bgbilling/BGBillingServer/dyn/
      - ./server/reports/:/opt/bgbilling/BGBillingServer/reports/
    deploy:
      restart_policy: { condition: on-failure, delay: 5s, max_attempts: 5, window: 180s}
    stop_grace_period: 30s

  scheduler:
    image: bgbilling/scheduler:7.1
    environment:
      TZ: 'Europe/Moscow'
      BGBILLING_MEMORY: '-Xmx256m'
    networks:
      - internal
    volumes:
      - ./server/data.properties:/opt/bgbilling/BGBillingServer/data/data.properties:ro
      - ./server/log4j.xml:/opt/bgbilling/BGBillingServer/data/log4j.xml:ro
      - ./server/log/:/opt/bgbilling/BGBillingServer/log/
    deploy:
      restart_policy: { condition: on-failure, delay: 5s, max_attempts: 5, window: 180s}
    stop_grace_period: 30s

  my:
    image: bgbilling/my:7.1
    environment:
      TZ: 'Europe/Moscow'
    ports:
      - "8081:8080"
    networks:
      - internal
    environment:
      WILDFLY_MEMORY: '-Xmx256m'
    volumes:
      - ./mybgbilling/log/:/opt/jboss/wildfly/standalone/log/


networks:
  internal:
    attachable: true

